# @SiteAPI_HostAddress = http://localhost:5099
@SiteAPI_HostAddress = https://publicapi-hre0e9a0fqcqebhu.northeurope-01.azurewebsites.net/

GET {{SiteAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
